name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZDg4YWM4Yy02MDIwLTQ0YWMtOGZiMC0zY2EwODIyNTgxZmUiLCJpYXQiOjE3OTA3NTUzMjEsImV4cCI6MTc5MDc1ODkyMX0.Hp3is8IEBZvF3B6MSCG5aEzT3cCPrUmA1W32BoqHE7Q
  - name: refreshToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZDg4YWM4Yy02MDIwLTQ0YWMtOGZiMC0zY2EwODIyNTgxZmUiLCJpYXQiOjE3OTA3NTUzMjEsImV4cCI6MTc5MTM2MDEyMX0.Ruov7LuP8V47PAnXwuGIUZHVrBcNqOV4jtIyv3EmuKg
