name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZDg4YWM4Yy02MDIwLTQ0YWMtOGZiMC0zY2EwODIyNTgxZmUiLCJpYXQiOjE3ODg0MjA1NzgsImV4cCI6MTc4ODQyNDE3OH0.TtCtKBaeHjxSdrPtIuG0T7RYbMcJT6sPziVDcPd5i8c
  - name: refreshToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZDg4YWM4Yy02MDIwLTQ0YWMtOGZiMC0zY2EwODIyNTgxZmUiLCJpYXQiOjE3ODg0MjA1NzgsImV4cCI6MTc4OTAyNTM3OH0.qAJGbZqzCKBy0YWpwzKjs8-vA8KXOancSKbHKcEulh8
